name: Run Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/**"
      - pubspec.yaml
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "lib/**"
      - "test/**"
      - pubspec.yaml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version: 3.24.4

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
